CREATE OR REPLACE TRIGGER IMPERIAL_UNITS_TRIGGER
BEFORE INSERT ON ATHLETES FOR EACH ROW 
BEGIN
    IF :NEW.HEIGHT IS NOT NULL
    THEN :NEW.HEIGHT_FEET := METR_TO_IMP.CM_TO_FT(:NEW.HEIGHT); END IF;
    IF :NEW.WEIGHT IS NOT NULL
    THEN :NEW.WEIGHT_LBS := METR_TO_IMP.KG_TO_LB(:NEW.WEIGHT); END IF;
END;