CREATE OR REPLACE TRIGGER BMI_TRIGGER
BEFORE INSERT ON ATHLETES FOR EACH ROW 
BEGIN
    IF :NEW.HEIGHT IS NOT NULL AND :NEW.WEIGHT IS NOT NULL
    THEN :NEW.BMI := CALCULATE_BMI(:NEW.WEIGHT, :NEW.HEIGHT);
    ELSE :NEW.BMI := NULL;
    END IF;
END;